name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '48 3 * * 6'  # Weekly

jobs:
  scheduled:
    runs-on: ubuntu-latest

    permissions:
      # Publish to github pages
      contents: read
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
        cache: 'pip'

    - name: Clone gtfs-osm-validator
      run: |
        git clone https://gitlab.com/stalker314314/gtfs-osm-validator.git

    - name: Clone gtfspy, and patch out broken dependency
      run: |
        git clone https://github.com/CxAalto/gtfspy.git
        cd gtfspy
        git checkout 24a60db1153efdc41ed9bb102aba039af1badf4b
        cd ..
        cat gtfspy-osmread-version.patch | patch -d gtfspy

    - name: Install gtfs-osm-validator dependencies
      run: |
        pip install -r requirements.txt gtfspy/
        
    - name: Fetch Burlington public gtfs data
      run: |
        curl -O https://opendata.burlington.ca/gtfs-rt/GTFS_Data.zip

    - name: Install burlington config into gtfs-osm-validator
      run: |
        cp -v burlington.py gtfs-osm-validator/src/configs/burlington.py

    - name: Run gtfs-osm-validator and produce text output
      run: |
        cd gtfs-osm-validator
        python src/main.py --config burlington ../GTFS_Data.zip > ../output.txt
        cd ..

    - name: Build markdown report
      run: |
        mkdir output/
        python report.py --read output.txt --write output/index.md
    
    - name: Setup pages
      uses: actions/configure-pages@v5
  
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v4
      with:
        # upload entire directory
        path: 'output'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
